# This is a basic workflow to help you get started with Actions

name: Automerge PDFs

# Controls when the action will run. 
on:
  pull_request:
    branches: [ PDF/* ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.12.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
