# This is a basic workflow to help you get started with Actions

name: Build PDF Revisioni

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags:
    - 'revisione-*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    name: Build PDFs and upload to release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        documenti: [analisi-dei-requisiti,norme-di-progetto,piano-di-progetto,piano-di-qualifica,studio-di-fattibilita]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Set up Git repository
        uses: actions/checkout@v2
      
      - name: Setup Python enviroment
        uses: actions/setup-python@v2.1.4
      
      ## ANALISI DEI REQUISITI
      - name: ${{ matrix.documenti }}
        run: echo "Start build ${{ matrix.documenti }}"
      
      - name: Add glossario to ${{ matrix.documenti }}
        run: python _glo_replace.py /${{ matrix.documenti }}/ glossario.txt
       
      - name: Compile analisi dei requisiti LaTeX document
        uses: damix48/latex-action@0.1
        with:
          working_directory: ${{ matrix.documenti }}/
          root_file: main.tex
      
      ## RELEASE
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      
      ## UPLOAD
      - name: Upload ${{ matrix.documenti }}
        id: upload-analisi
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ matrix.documenti }}/main.pdf
          asset_name: ${{ matrix.documenti }}.pdf
          asset_content_type: application/pdf
