# This is a basic workflow to help you get started with Actions

name: Build PDF Revisioni

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags:
    - 'revisione-*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build PDFs and upload to release
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Set up Git repository
        uses: actions/checkout@v2
      
      - name: Setup Python enviroment
        uses: actions/setup-python@v2.1.4
      
      ## ANALISI DEI REQUISITI
      - name: Analisi dei requisiti
        run: echo "Start build analisi dei requisiti"
      
      - name: Add glossario to analisi dei requisiti
        run: python _glo_replace.py /analisi-dei-requisiti/ glossario.txt
       
      - name: Compile analisi dei requisiti LaTeX document
        uses: damix48/latex-action@0.1
        with:
          working_directory: analisi-dei-requisiti/
          root_file: main.tex
      
      ## NORME DI PROGETTO
      - name: Norme di progetto
        run: echo "Start build norme di progetto"
      
      - name: Add glossario to norme di progetto
        run: python _glo_replace.py /norme-di-progetto/ glossario.txt
        
      - name: Compile norme di progetto LaTeX document
        uses: damix48/latex-action@0.1
        with:
          working_directory: norme-di-progetto/
          root_file: main.tex
        
      ## PIANO DI PROGETTO
      - name: Piano di progetto
        run: echo "Start build piano di progetto"
      
      - name: Add glossario to piano di progetto
        run: python _glo_replace.py /piano-di-progetto/ glossario.txt
        
      - name: Compile piano di progetto LaTeX document
        uses: damix48/latex-action@0.1
        with:
          working_directory: piano-di-progetto/
          root_file: main.tex

      ## PIANO DI QUALIFICA
      - name: Piano di qualifica
        run: echo "Start build piano di qualifica"
      
      - name: Add glossario to piano di qualifica
        run: python _glo_replace.py /piano-di-qualifica/ glossario.txt
        
      - name: Compile piano di qualifica LaTeX document
        uses: damix48/latex-action@0.1
        with:
          working_directory: piano-di-qualifica/
          root_file: main.tex

      ## STUDIO DI FATTIBILITÀ
      - name: Studio di fattibilità
        run: echo "Start build studio di fattibilita"
      
      - name: Add glossario to studio di fattibilità
        run: python _glo_replace.py /studio-di-fattibilita/ glossario.txt
        
      - name: Compile studio di fattibilità LaTeX document
        uses: damix48/latex-action@0.1
        with:
          working_directory: studio-di-fattibilita/
          root_file: main.tex

      ## GLOSSARIO
      - name: Glossario
        run: echo "Start build Glossario"
        
      - name: Compile glossario LaTeX document
        uses: damix48/latex-action@0.1
        with:
          working_directory: glossario/
          root_file: main.tex

      ## VERBALE verbale-interno_2020-12-09
      - name: verbale-interno_2020-12-09
        run: echo "Start build verbale-interno_2020-12-09"
      
      - name: Add glossario to verbale-interno_2020-12-09
        run: python _glo_replace.py /verbali/verbale-interno_2020-12-09/ glossario.txt
        
      - name: Compile verbale-interno_2020-12-09 LaTeX document
        uses: damix48/latex-action@0.1
        with:
          working_directory: verbali/verbale-interno_2020-12-09/
          root_file: main.tex

      ## VERBALE verbale-interno_2020-12-16
      - name: verbale-interno_2020-12-16
        run: echo "Start build verbale-interno_2020-12-16"
      
      - name: Add glossario to verbale-interno_2020-12-16
        run: python _glo_replace.py /verbali/verbale-interno_2020-12-16/ glossario.txt
        
      - name: Compile verbale-interno_2020-12-16 LaTeX document
        uses: damix48/latex-action@0.1
        with:
          working_directory: verbali/verbale-interno_2020-12-16/
          root_file: main.tex

      ## VERBALE verbale-interno_2021-01-05
      - name: verbale-interno_2021-01-05
        run: echo "Start build verbale-interno_2021-01-05"
      
      - name: Add glossario to verbale-interno_2021-01-05
        run: python _glo_replace.py /verbali/verbale-interno_2021-01-05/ glossario.txt
        
      - name: Compile verbale-interno_2021-01-05 LaTeX document
        uses: damix48/latex-action@0.1
        with:
          working_directory: verbali/verbale-interno_2021-01-05/
          root_file: main.tex

      ## VERBALE verbale-interno_2021-01-13
      - name: verbale-interno_2021-01-13
        run: echo "Start build verbale-interno_2021-01-13"
      
      - name: Add glossario to verbale-interno_2021-01-13
        run: python _glo_replace.py /verbali/verbale-interno_2021-01-13/ glossario.txt
        
      - name: Compile verbale-interno_2021-01-13 LaTeX document
        uses: damix48/latex-action@0.1
        with:
          working_directory: verbali/verbale-interno_2021-01-13/
          root_file: main.tex

      ## VERBALE verbale-interno_2021-01-30
      - name: verbale-interno_2021-01-30
        run: echo "Start build verbale-interno_2021-01-30"
      
      - name: Add glossario to verbale-interno_2021-01-30
        run: python _glo_replace.py /verbali/verbale-interno_2021-01-30/ glossario.txt
        
      - name: Compile verbale-interno_2021-01-30 LaTeX document
        uses: damix48/latex-action@0.1
        with:
          working_directory: verbali/verbale-interno_2021-01-30/
          root_file: main.tex

      ## VERBALE verbale-interno_2021-02-05
      - name: verbale-interno_2021-02-05
        run: echo "Start build verbale-interno_2021-02-05"
      
      - name: Add glossario to verbale-interno_2021-02-05
        run: python _glo_replace.py /verbali/verbale-interno_2021-02-05/ glossario.txt
        
      - name: Compile verbale-interno_2021-02-05 LaTeX document
        uses: damix48/latex-action@0.1
        with:
          working_directory: verbali/verbale-interno_2021-02-05/
          root_file: main.tex

      ## VERBALE verbale-interno_2021-02-10
      - name: verbale-interno_2021-02-10
        run: echo "Start build verbale-interno_2021-02-10"
      
      - name: Add glossario to verbale-interno_2021-02-10
        run: python _glo_replace.py /verbali/verbale-interno_2021-02-10/ glossario.txt
        
      - name: Compile verbale-interno_2021-02-10 LaTeX document
        uses: damix48/latex-action@0.1
        with:
          working_directory: verbali/verbale-interno_2021-02-10/
          root_file: main.tex

      ## VERBALE verbale-interno_2021-02-25
      - name: verbale-interno_2021-02-25
        run: echo "Start build verbale-interno_2021-02-25"
      
      - name: Add glossario to verbale-interno_2021-02-25
        run: python _glo_replace.py /verbali/verbale-interno_2021-02-25/ glossario.txt
        
      - name: Compile verbale-interno_2021-02-25 LaTeX document
        uses: damix48/latex-action@0.1
        with:
          working_directory: verbali/verbale-interno_2021-02-15/
          root_file: main.tex

      ## VERBALE verbale-esterno_2021-02-02
      - name: verbale-esterno_2021-02-02
        run: echo "Start build verbale-esterno_2021-02-02"
      
      - name: Add glossario to verbale-esterno_2021-02-02
        run: python _glo_replace.py /verbali/verbale-esterno_2021-02-02/ glossario.txt
        
      - name: Compile verbale-esterno_2021-02-02 LaTeX document
        uses: damix48/latex-action@0.1
        with:
          working_directory: verbali/verbale-esterno_2021-02-02/
          root_file: main.tex

      ## RELEASE
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false      
      
      ## UPLOAD
      - name: Upload Analisi dei requisiti
        id: upload-analisi
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: analisi-dei-requisiti/main.pdf
          asset_name: analisi-dei-requisiti.pdf
          asset_content_type: application/pdf      
      
      - name: Upload Norme di progetto
        id: upload-norme
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: norme-di-progetto/main.pdf
          asset_name: norme-di-progetto.pdf
          asset_content_type: application/pdf
      
      - name: Upload Piano di progetto
        id: upload-piano-progetto
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: piano-di-progetto/main.pdf
          asset_name: piano-di-progetto.pdf
          asset_content_type: application/pdf

      - name: Upload Piano di qualifica
        id: upload-piano-qualifica
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: piano-di-qualifica/main.pdf
          asset_name: piano-di-qualifica.pdf
          asset_content_type: application/pdf

      - name: Upload Glossario
        id: upload-glossario
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: glossario/main.pdf
          asset_name: glossario.pdf
          asset_content_type: application/pdf

      - name: Upload Studio di fattibilità
        id: upload-studio
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: studio-di-fattibilita/main.pdf
          asset_name: studio-di-fattibilita.pdf
          asset_content_type: application/pdf

      - name: Upload verbale-interno_2020-12-09
        id: upload-verbale-interno_2020-12-09
        
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: verbali/verbale-interno_2020-12-09/main.pdf
          asset_name: verbale-interno_2020-12-09.pdf
          asset_content_type: application/pdf
          
      - name: Upload verbale-interno_2020-12-16
        id: upload-verbale-interno_2020-12-16
        
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: verbali/verbale-interno_2020-12-16/main.pdf
          asset_name: verbale-interno_2020-12-16.pdf
          asset_content_type: application/pdf

      - name: Upload verbale-interno_2021-01-05
        id: upload-verbale-interno_2021-01-05
        
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path: verbali/verbale-interno_2021-01-05/main.pdf
          asset_name: verbale-interno_2021-01-05.pdf
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_content_type: application/pdf

      - name: Upload verbale-interno_2021-01-13
        id: upload-verbale-interno_2021-01-13
        
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path: verbali/verbale-interno_2021-01-13/main.pdf
          asset_name: verbale-interno_2021-01-13.pdf
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_content_type: application/pdf
          
      - name: Upload verbale-interno_2021-01-30
        id: upload-verbale-interno_2021-01-30
        
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path: verbali/verbale-interno_2021-01-30/main.pdf
          asset_name: verbale-interno_2021-01-30.pdf
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_content_type: application/pdf
          
      - name: Upload verbale-interno_2021-02-05
        id: upload-verbale-interno_2021-02-05
        
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path: verbali/verbale-interno_2021-02-05/main.pdf
          asset_name: verbale-interno_2021-02-05.pdf
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_content_type: application/pdf

      - name: Upload verbale-interno_2021-02-10
        id: upload-verbale-interno_2021-02-10
        
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path: verbali/verbale-interno_2021-02-10/main.pdf
          asset_name: verbale-interno_2021-02-10.pdf
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_content_type: application/pdf
          
      - name: Upload verbale-interno_2021-02-25
        id: upload-verbale-interno_2021-02-25
        
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path: verbali/verbale-interno_2021-02-25/main.pdf
          asset_name: verbale-interno_2021-02-25.pdf
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_content_type: application/pdf
      
      - name: Upload verbale-esterno_2021-02-02
        id: upload-verbale-esterno_2021-02-02
        
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path: verbali/verbale-esterno_2021-02-02/main.pdf
          asset_name: verbale-esterno_2021-02-02.pdf
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_content_type: application/pdf
