# This is a basic workflow to help you get started with Actions

name: Build PDF Revisioni

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags:
    - 'revisione-*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build PDFs and upload to release
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Set up Git repository
        uses: actions/checkout@v2
      
      - name: Setup Python enviroment
        uses: actions/setup-python@v2.1.4
      
      ## ANALISI DEI REQUISITI
      - name: Analisi dei requisiti
        run: echo "Start build analisi dei requisiti"
      
      - name: Add glossario
        run: python _glo_replace.py /analisi-dei-requisiti/ glossario.txt
       
      - name: Compile LaTeX document
        uses: damix48/latex-action@0.1
        with:
          working_directory: analisi-dei-requisiti/
          root_file: main.tex
      
      ## ANALISI DEI REQUISITI
      - name: Norme di progetto
        run: echo "Start build norme di progetto"
      
      - name: Add glossario
        run: python _glo_replace.py /norme-di-progetto/ glossario.txt
        
      - name: Compile LaTeX document
        uses: damix48/latex-action@0.1
        with:
          working_directory: norme-di-progetto/
          root_file: main.tex
        
        ## RELEASE
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      
      - name: Upload Analisi dei requisiti
        id: upload-analisi
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: analisi-dei-requisiti/main.pdf
          asset_name: analisi-dei-requisiti.pdf
          asset_content_type: application/pdf      
      
      - name: Upload Norme di progetto
        id: upload-norme
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: norme-di-progetto/main.pdf
          asset_name: norme-di-progetto.pdf
          asset_content_type: application/pdf
