# This is a basic workflow to help you get started with Actions

name: Build PDF Norme di progetto

# Controls when the action will run. 
on:
  push:
    paths:
    - norme-di-progetto/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Set up Git repository
        uses: actions/checkout@v2
        
      ## NORME DI PROGETTO
      - name: Compile Norme di progetto
        uses: vinay0410/tectonic-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tex_path: norme-di-progetto/main.tex
      
      - name: Commit files
        run: |
          cp norme-di-progetto/main.pdf norme-di-progetto.pdf
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add norme-di-progetto/main.pdf norme-di-progetto.pdf
          git commit -m "Generati PDF delle norme di progetto"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
