name: Calcola indice di Gulpease

on:

  workflow_dispatch:
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Calcola Gulpease
        uses: strang3nt/GulpeaseAction@master

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Optional but recommended
          # Defaults to "Apply automatic changes"
          commit_message: Calcolato Gulpease

          # Optional glob pattern of files which should be added to the commit
          # Defaults to all (.)
          # See the `pathspec`-documentation for git
          # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
          # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
          file_pattern: README.md

          # Optional commit user and author settings
          commit_user_name: My GitHub Actions Bot # defaults to "GitHub Actions"
          commit_user_email: my-github-actions-bot@example.org # defaults to "actions@github.com"
          commit_author: Author <actions@github.com> # defaults to author of the commit that triggered the run
          
          # Optional: Disable dirty check and always try to create a commit and push
          skip_dirty_check: true    
          
          # Optional: Skip internal call to `git fetch`
          skip_fetch: true