# This is a basic workflow to help you get started with Actions

name: Build PDF Piano di qualifica

# Controls when the action will run. 
on:
  push:
    branches: [ master ]
    paths:
    - 'piano-di-qualifica/**'
    - '!**.pdf'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Set up Git repository
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2.1.4
      
      - name: Add glossario
        run: python _glo_replace.py /piano-di-qualifica/ glossario.txt

      - name: Compile Piano di qualifica
        uses: vinay0410/tectonic-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tex_path: piano-di-qualifica/main.tex
      
      - name: Remove previous tag and release
        uses: dev-drprasad/delete-tag-and-release@v0.1.2
        with:
          delete_release: true # default: false
          tag_name: wip/piano-di-qualifica # tag name to delete
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: true
          tag_name: wip/piano-di-qualifica
          release_name: '[WIP] PDF Piano di qualifica'
      
      - name: Upload in release
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: piano-di-qualifica/main.pdf
          asset_name: piano-di-qualifica.pdf
          asset_content_type: application/pdf
